version: "3.8"

services:
  # Django service
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=ecommerce.settings
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - app_network

  # Django service for running tests
  web-test:
    build: .
    entrypoint: ["/app/docker-entrypoint-test.sh"]  # Use the test entrypoint script
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=ecommerce.settings
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - app_network

  # PostgreSQL service
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
